{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appointments-app.postgresql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appointments-app.postgresql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "appointments-app.postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "appointments-app.postgresql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: postgresql
        image: postgres:16
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.postgresql.port }}
          name: postgresql
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.admin.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.admin.password }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        {{- if .Values.postgresql.config }}
        - name: postgresql-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        {{- end }}
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgresql.admin.username }}
            - -d
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgresql.admin.username }}
            - -d
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: {{ include "appointments-app.postgresql.name" . }}-pvc
      {{- if .Values.postgresql.config }}
      - name: postgresql-config
        configMap:
          name: {{ include "appointments-app.postgresql.name" . }}-config
      {{- end }}
{{- end }}