apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appointments-app.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appointments-app.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | default "M2RiNzY4MGEwOWQ1N2UzNTRkOTUxM2U2MGE2ZmJlNzkzNzY4Y2ZlZWQ1MTBlOGE5MmZlZWM4MDlhM2UzMjE1Yw==" | quote }}
  vatcheck-api-key: {{ .Values.secrets.vatcheckApiKey | default "dmF0X2xpdmVwSng3aktRZ04wNEMyTzlkYlllNThMeWhYVEV0SkpqeEw5cHF3akdQ" | quote }}

  # Only required for production with Azure Event Hubs
  eventhubs-connection-string: {{ .Values.secrets.eventHubsConnectionString | default "" | quote }}

  # gRPC URL for Availability Service
  availability-service-grpc-url: {{ printf "http://%s-availability:5001" (include "appointments-app.fullname" .) | b64enc | quote }}