{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appointments-app.postgresql.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appointments-app.postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.postgresql.port }}
    targetPort: {{ .Values.postgresql.port }}
    protocol: TCP
    name: postgresql
  selector:
    {{- include "appointments-app.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}