apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: kafka
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: client
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: controller
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app.kubernetes.io/name: kafka
  publishNotReadyAddresses: true
