{{- if and .Values.fluentbit.enabled (eq .Values.fluentbit.kind "DaemonSet") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentbit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-fluentbit
    app.kubernetes.io/component: fluent-bit
    {{- with .Values.fluentbit.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-fluentbit
  template:
    metadata:
      annotations:
        {{- with .Values.fluentbit.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-fluentbit
        app.kubernetes.io/component: fluent-bit
        {{- with .Values.fluentbit.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}-fluentbit
      {{- with .Values.fluentbit.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fluentbit.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fluentbit.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fluent-bit
          image: {{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}
          imagePullPolicy: {{ .Values.fluentbit.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- with .Values.fluentbit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.fluentbit.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: varjournal
              mountPath: /run/log/journal
              readOnly: true
            {{- if .Values.fluentbit.extraVolumeMounts }}
            {{- toYaml .Values.fluentbit.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: fluent-bit-config
          configMap:
            name: {{ .Release.Name }}-fluentbit-config
        - name: varjournal
          hostPath:
            path: /run/log/journal
        {{- if .Values.fluentbit.extraVolumes }}
        {{- toYaml .Values.fluentbit.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}