{{- if .Values.fluentbit.enabled }}
{{- if .Values.fluentbit.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-fluentbit
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-fluentbit
    app.kubernetes.io/component: fluent-bit
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-fluentbit
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-fluentbit
    app.kubernetes.io/component: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-fluentbit
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-fluentbit
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}