{{- if .Values.fluentbit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-fluentbit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-fluentbit
    app.kubernetes.io/component: fluentbit
{{- end }}