apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-loki
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.loki.serviceAccount.annotations }}
    {{- toYaml .Values.loki.serviceAccount.annotations | nindent 4 }}
    {{- end }}