apiVersion: v1
kind: Service
metadata:
  name: monitoring-loki-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: backend
  annotations:
    {{- if .Values.loki.service.annotations }}
    {{- toYaml .Values.loki.service.annotations | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.loki.service.port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: 9095
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend