apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monitoring-loki
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: backend
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.loki.singleBinary.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  serviceName: monitoring-loki-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/loki/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: monitoring-loki
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/config/config.yaml
          ports:
            - name: http-metrics
              containerPort: {{ .Values.loki.structuredConfig.server.http_listen_port }}
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.loki.singleBinary.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: storage
              mountPath: /loki
            - name: tmp
              mountPath: /tmp
            - name: wal
              mountPath: /wal
      terminationGracePeriodSeconds: 4800
      volumes:
        - name: config
          configMap:
            name: monitoring-loki-config
        - name: tmp
          emptyDir: {}
        - name: wal
          emptyDir: {}
  {{- if .Values.loki.singleBinary.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage
        labels:
          app.kubernetes.io/name: loki
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: backend
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.loki.singleBinary.persistence.size }}
        {{- if .Values.loki.singleBinary.persistence.storageClass }}
        storageClassName: {{ .Values.loki.singleBinary.persistence.storageClass }}
        {{- end }}
  {{- end }}