{
 "title": "Appointments API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Requests",
   "type": "timeseries",
   "description": "Total requests per second in the last 5 minutes aggregated per service",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app_kubernetes_io_name) (rate(http_requests_received_total{namespace=\"appointments-app\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API response times",
   "type": "timeseries",
   "description": "Average HTTP request duration per service over the last 5 minutes",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (\r\n  rate(http_request_duration_seconds_sum{namespace=\"appointments-app\"}[5m])\r\n)\r\n/\r\nsum by (app_kubernetes_io_name) (\r\n  rate(http_request_duration_seconds_count{namespace=\"appointments-app\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Percentage of CPU used on average over the last 5 minutes",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(container_cpu_usage_seconds_total{namespace=\"appointments-app\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Currently used bytes",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"appointments-app\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}